amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.01
    alpha2: 0.1
    alpha3: 0.05
    alpha4: 0.9
    alpha5: 0.04
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 16.0
    laser_max_range: 5.0
    laser_min_range: 0.25
    laser_model_type: "beam"
    max_beams: 200
    max_particles: 4000
    min_particles: 500
    odom_frame_id: "base_odom"
    pf_err: 0.02
    pf_z: 0.85
    recovery_alpha_fast: 0.05
    recovery_alpha_slow: 0.001
    resample_interval: 2
    robot_model_type: "omnidirectional"
    save_pose_rate: 0.5
    sigma_hit: 0.02
    tf_broadcast: true
    transform_tolerance: 0.05
    update_min_a: 0.06
    update_min_d: 0.025
    z_hit: 0.7
    z_max: 0.001
    z_rand: 0.059
    z_short: 0.24
    initial_pose_x: 0
    initial_pose_y: 0
    initial_pose_a: 0
    initial_cov_xx: 0.4
    initial_cov_yy: 0.4
    initial_cov_aa: 0.6

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_xml_filename: "bt_navigator.xml"

dwb_controller:
  ros__parameters:
    use_sim_time: False
    debug_trajectory_details: True
    controller_frequency: 10.0
    min_vel_x: -0.4
    min_vel_y: -0.4
    max_vel_x: 0.4
    max_vel_y: 0.4
    max_vel_theta: 0.5
    min_speed_xy: 0.1
    max_speed_xy: 0.5
    min_speed_theta: 0.1
    min_x_velocity_threshold: 0.001
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    acc_lim_x: 3.0
    acc_lim_y: 3.0
    acc_lim_theta: 2.5
    decel_lim_x: -3.0
    decel_lim_y: -3.0
    decel_lim_theta: -2.5
    vx_samples: 13
    vy_samples: 13
    vtheta_samples: 19
    sim_time: 1.0
    linear_granularity: 0.04
    xy_goal_tolerance: 0.15
    transform_tolerance: 0.2
    critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    BaseObstacle.scale: 0.02
    PathAlign.scale: 0.0
    GoalAlign.scale: 0.0
    PathDist.scale: 32.0
    GoalDist.scale: 10.0
    RotateToGoal.scale: 32.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      global_frame: map
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 2
      height: 2
      resolution: 0.030
      robot_radius: 0.17
      footprint_padding: 0.02
      update_frequency: 5.0
      publish_frequency: 2.0
      inflation_layer.cost_scaling_factor: 7.0
      inflation_layer.inflation_radius: 0.3
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        inf_is_valid: True
        obstacle_range: 2.0
        raytrace_range: 5.0

  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      robot_radius: 0.22
      inflation_layer.cost_scaling_factor: 7.0
      inflation_layer.inflation_radius: 0.3
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        inf_is_valid: True
        obstacle_range: 2.0
        raytrace_range: 5.0
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "turtlebot3_world.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names: ['map_server', 'amcl',
                 'world_model', 'dwb_controller',
                 'navfn_planner', 'bt_navigator']

lifecycle_manager_service_client:
  ros__parameters:
    use_sim_time: False

lifecycle_manager_client_service_client:
  ros__parameters:
    use_sim_time: False

navfn_planner:
  ros__parameters:
    use_sim_time: False
    tolerance: 0.0
    use_astar: false

navfn_planner_GetCostmap_client:
  ros__parameters:
    use_sim_time: False

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

world_model:
  ros__parameters:
    use_sim_time: False
